export const projects = [
    {
        id: "1",
        title: "Evalujeu",
        shortdescription: "Evalujeu est un dispositif de prévention du jeu excessif. Il propose aux joueurs de tester leur pratique de jeu en répondant à un questionnaire. C’est l’ANJ (l’autorité nationale des jeux) qui gère la plateforme.",
        imageHero: "/images/projetPage/evalujeu-hero.png",
        role: "Front-End",
        contexte:"Agence Digital",
        annee: "2022",
        stackLogo: "/images/drupal-logo.png",
        stackLogo2: "/images/tailwindcss-logo.png",
        stackLogo3: "/images/jira-logo.png",
        description: "Lancé en 2015, Evalujeu est un dispositif de prévention du jeu excessif. Il propose aux joueurs de tester leur pratique de jeu en répondant à un questionnaire. Ce dernier permet de déterminer le niveau de risque du joueur et de lui proposer des conseils pour maintenir une pratique récréative. J’ai eu l’opportunité de travailler sur l’intégration de la nouvelle identité visuelle du site lors de mon contrat chez ISOBAR (Agence digitale - Groupe Dentsu).  Le site est également conforme a la normes RGAA.",
        imgAbout: "/images/projetPage/evalujeu-about.png",
        fontTitle: "changa-one",
        fontText: "assistant",
        colors: ["2B0D56","B1237A","00628E", "0B6948","0B6948","B19313"],
        imgAbout2: "/images/projetPage/evalujeu-about-1.png",
        website: "https://www.evalujeu.fr/"
    },
    {
        id: "2",
        title: "Ecarmotors",
        shortdescription: "Site de vente pour un garage spécialisé dans les voitures premium et de luxe, réalisé en collaboration avec l'agence Radiant. Utilisation de Wordpress avec un plugin sur mesure pour l'importation des véhicules via la plateforme de gestion des stocks du client. Participation à l'intégration front-end.",
        imageHero: "/images/projetPage/ecarmotors-hero.png",
        role: "Full Stack",
        contexte:"Freelance",
        annee: "2023",
        stackLogo: "/images/wordpress-logo.png",
        stackLogo2: "/images/divi-logo.png",
        stackLogo3: "/images/trello-logo.png",
        description: "J'ai collaboré avec l'agence Radiant pour créer un site de vente destiné à un garage qui propose des voitures premium et de luxe. Nous avons utilisé Wordpress comme base de développement pour sa flexibilité et sa robustesse. Mon rôle principal a été de m'occuper du back-end du site. Pour répondre aux besoins spécifiques du client, j'ai développé un plugin sur mesure qui permet d'importer les véhicules directement depuis leur plateforme de gestion des stocks. Ce plugin assure une synchronisation fluide et en temps réel des données, simplifiant ainsi la gestion des véhicules en vente sur le site. En outre, j'ai également apporté mon expertise en front-end pour assister à l'intégration des divers éléments visuels et fonctionnels, garantissant une expérience utilisateur fluide et intuitive.",
        imgAbout: "/images/projetPage/ecarmotors-about-1.png",
        fontTitle: "cantarell",
        fontText: "montserrat",
        colors: ["0066ff","000000","ffffff"],
        imgAbout2: "/images/projetPage/ecarmotors-about-1.png",
        website: "https://www.ecarmotors.fr/"
    },
    // Ajoutez plus de projets ici
];
