export const projects = [
    {
        id: "1",
        title: "Evalujeu",
        shortdescription: "Evalujeu est un dispositif de prévention du jeu excessif. Il propose aux joueurs de tester leur pratique de jeu en répondant à un questionnaire. C'est l'ANJ (l'autorité nationale des jeux) qui gère la plateforme.",
        imageHero: "/images/projetPage/evalujeu-hero.png",
        homeImage: "/images/evalujeu_sample_img.png",
        homeImage2: "/images/evalujeu_sample_img_2.png",
        homeImageWidth: 2560,
        homeImageHeight: 1394,
        homeImage2Width: 2560,
        homeImage2Height: 1413,
        role: "Front-End",
        contexte: "Agence Digital",
        annee: "2022",
        stackLogo: "/images/drupal-logo.png",
        stackLogo2: "/images/tailwindcss-logo.png",
        stackLogo3: "/images/jira-logo.png",
        description: "Lancé en 2015, Evalujeu est un dispositif de prévention du jeu excessif. Il propose aux joueurs de tester leur pratique de jeu en répondant à un questionnaire. Ce dernier permet de déterminer le niveau de risque du joueur et de lui proposer des conseils pour maintenir une pratique récréative. J'ai eu l'opportunité de travailler sur l'intégration de la nouvelle identité visuelle du site lors de mon contrat chez ISOBAR (Agence digitale - Groupe Dentsu).  Le site est également conforme a la normes RGAA.",
        imgAbout: "/images/projetPage/evalujeu-about.png",
        fontTitle: "changa-one",
        fontText: "assistant",
        colors: ["2B0D56", "B1237A", "00628E", "0B6948", "0B6948", "B19313"],
        imgAbout2: "/images/projetPage/evalujeu-about-1.png",
        website: "https://www.evalujeu.fr/"
    },
    {
        id: "2",
        title: "Ecarmotors",
        shortdescription: "Site de vente pour un garage spécialisé dans les voitures premium et de luxe, réalisé en collaboration avec l'agence Radiant. Utilisation de Wordpress avec un plugin sur mesure pour l'importation des véhicules via la plateforme de gestion des stocks du client. Participation à l'intégration front-end.",
        imageHero: "/images/projetPage/ecarmotors-hero.png",
        homeImage: "/images/ecarmotors-sample_img.png",
        homeImage2: "/images/ecarmotors-sample_img_1.png",
        homeImageWidth: 2560,
        homeImageHeight: 1794,
        homeImage2Width: 2560,
        homeImage2Height: 960,
        role: "Full Stack",
        contexte: "Freelance",
        annee: "2023",
        stackLogo: "/images/wordpress-logo.png",
        stackLogo2: "/images/divi-logo.png",
        stackLogo3: "/images/trello-logo.png",
        description: "J'ai collaboré avec l'agence Radiant pour créer un site de vente destiné à un garage qui propose des voitures premium et de luxe. Nous avons utilisé Wordpress comme base de développement pour sa flexibilité et sa robustesse. Mon rôle principal a été de m'occuper du back-end du site. Pour répondre aux besoins spécifiques du client, j'ai développé un plugin sur mesure qui permet d'importer les véhicules directement depuis leur plateforme de gestion des stocks. Ce plugin assure une synchronisation fluide et en temps réel des données, simplifiant ainsi la gestion des véhicules en vente sur le site. En outre, j'ai également apporté mon expertise en front-end pour assister à l'intégration des divers éléments visuels et fonctionnels, garantissant une expérience utilisateur fluide et intuitive.",
        imgAbout: "/images/projetPage/ecarmotors-about.png",
        fontTitle: "cantarell",
        fontText: "montserrat",
        colors: ["0066ff", "000000", "ffffff"],
        imgAbout2: "/images/projetPage/ecarmotors-about-1.png",
        website: "https://www.ecarmotors.fr/"
    },
    {
        id: "3",
        title: "Fika Beauty",
        shortdescription: "Fika Beauty est un site WordPress développé pour un institut de beauté parisien, intégrant un design responsive avec Divi, une solution de réservation en ligne via Amelia, des paiements sécurisés avec PayPal, et une conformité RGPD grâce à la gestion des cookies et des données personnelles.",
        imageHero: "/images/projetPage/fika-hero.png",
        homeImage: "/images/fika_sample_img.png",
        homeImage2: "/images/fika_sample_img_2.png",
        homeImageWidth: 2560,
        homeImageHeight: 1394,
        homeImage2Width: 2560,
        homeImage2Height: 1413,
        role: "Full Stack",
        contexte: "Freelance",
        annee: "2024",
        stackLogo: "/images/wordpress-logo.png",
        stackLogo2: "/images/divi-logo.png",
        stackLogo3: "/images/logo_amelia_small.png",
        description: "Le site à été développé pour un institut de beauté parisien. J'ai utilisé Wordpress avec Divi pour le design des pages web ce qui m'a permit de proposer la meilleur expérience utilisateur possible. J'ai fais le choix d'utiliser le plugin Amelia pour gérer les réservations en ligne, Amelia est un plugin très complet et facile à utiliser. Le site est également conforme à la norme RGPD.",
        imgAbout: "/images/projetPage/fika-about.png",
        fontTitle: "montserrat",
        fontText: "raleway",
        colors: ["fcd0c5", "131312", "fdfdfd"],
        imgAbout2: "/images/projetPage/fika-about-1.png",
        website: "https://fika-beauty.fr/"
    },
    {
        id: "4",
        title: "Carbonestone",
        shortdescription: "CarboneStone repose sur deux sites WordPress (Particulier et Pro) développés sous Divi, intégrant un système de devis dynamique basé sur Forminator Pro, alimenté par des grilles tarifaires CSV et un recalcul sécurisé côté serveur. Le site Pro inclut un espace client avec gestion des marges personnalisées et historique des devis, le tout soutenu par une logique métier centralisée en PHP et des échanges AJAX pour garantir cohérence et fiabilité des montants.",
        imageHero: "/images/projetPage/carbonestone-hero.png",
        homeImage: "/images/carbonestone_sample_img.png",
        homeImage2: "/images/carbonestone_sample_img_2.png",
        homeImageWidth: 2560,
        homeImageHeight: 1794,
        homeImage2Width: 2560,
        homeImage2Height: 960,
        role: "Full Stack",
        contexte: "Freelance",
        annee: "2025",
        stackLogo: "/images/wordpress-logo.png",
        stackLogo2: "/images/divi-logo.png",
        stackLogo3: "/images/logo_forminator.svg",
        description: "CarboneStone repose sur deux sites WordPress distincts (Particulier et Pro) développés sous Divi, intégrant une logique métier sur mesure en PHP et JavaScript. Le site Particulier embarque un système de devis dynamique construit avec Forminator Pro, alimenté par des grilles tarifaires importées via CSV (Dekton, Quartz, Céramique, Granit), avec recalcul sécurisé côté serveur, gestion conditionnelle des façonnages via l'API Forminator, validation anti-fraude et génération automatique de PDF personnalisés. Le site Pro ajoute un espace authentifié via WP User Manager permettant aux professionnels de définir leurs marges, générer leurs devis personnalisés et consulter leur historique, le tout appuyé par des endpoints AJAX et une logique de calcul centralisée pour garantir cohérence et fiabilité des montants.",
        imgAbout: "/images/projetPage/carbonestone-about.png",
        fontTitle: "josefin-sans",
        fontText: "open-sans",
        colors: ["23e8c2", "161515", "fffaff"],
        imgAbout2: "/images/projetPage/carbonestone-about-1.png",
        website: "https://carbonestone.fr/"
    },
    {
        id: "5",
        title: "Larevued'geek",
        shortdescription: "LaRevueD'Geek est un site développé sous WordPress avec Elementor Pro et un thème enfant personnalisé. Le projet intègre Simple Custom Fields, plusieurs APIs externes pour afficher du contenu dynamique ainsi que des développements spécifiques en PHP, JavaScript et CSS pour adapter l'expérience éditoriale et automatiser certaines sections du site.",
        imageHero: "/images/projetPage/larevuedgeek-hero.png",
        homeImage: "/images/larevuedgeek_sample_img.png",
        homeImage2: "/images/larevuedgeek_sample_img_2.png",
        homeImageWidth: 2560,
        homeImageHeight: 1394,
        homeImage2Width: 2560,
        homeImage2Height: 1413,
        role: "Full Stack",
        contexte: "Freelance",
        annee: "2025",
        stackLogo: "/images/wordpress-logo.png",
        stackLogo2: "/images/elementor-logo.png",
        stackLogo3: "/images/acf-logo.svg",
        description: "LaRevueD'Geek est développé sous WordPress avec Elementor Pro pour la conception des pages et l'intégration de layouts personnalisés. Le site utilise Simple Custom Fields pour gérer des contenus dynamiques comme les notes de produits, les citations littéraires ou certaines données éditoriales. Plusieurs APIs externes sont intégrées afin d'afficher automatiquement des contenus comme les sorties de jeux vidéo ou de films. Beaucoup d'ajustements PHP, JavaScript et CSS ont été réalisés via un thème enfant afin de créer des composants personnalisés, automatiser certaines sections du site et améliorer l'expérience utilisateur.",
        imgAbout: "/images/projetPage/larevuedgeek-about.png",
        fontTitle: "montserrat",
        fontText: "inter",
        colors: ["F5E663", "9457B5", "414141"],
        imgAbout2: "/images/projetPage/larevuedgeek-about-1.png",
        website: "https://www.larevuedgeek.fr"
    },
];

export function getProjectById(id) {
    return projects.find((project) => project.id === id);
}
